Repository AY2425S1-CS2103-F11-1/tp, pull requests merged in 2024-11, with the labels that each got.

#213 Change EditAssignmentCommand and its parser for new feature design
  src/main/java/seedu/address/logic/commands/EditAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/EditAssignmentCommandParser.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/AssignmentName.java
  src/main/java/seedu/address/model/student/Student.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditAssignmentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditAssignmentCommandParserTest.java
  src/test/java/seedu/address/testutil/EditAssignmentDescriptorBuilder.java
Labels: type.Bug, severity.High

#162 Update code to test Student Class
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/student/StudentTest.java
Labels: type.Task, priority.Medium

#219 Update Ug to match TAchy specifications
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/student_index.png
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/TAchy_logo.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentDetailsPanel.fxml
  src/main/resources/view/StudentListCard.fxml
Labels: alpha-bug

#215 Update UI to be consistent for list view
  docs/DeveloperGuide.md
  src/main/resources/view/DarkTheme.css
Labels: alpha-bug

#214 Fix help message
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/testutil/StudentUtil.java
Labels: priority.High, alpha-bug

#221 Update user guide for shortened prefixes and a new image
  docs/UserGuide.md
  docs/images/add_assignment_image.jpg
Labels: severity.Medium

#223 Update UG
  docs/UserGuide.md
  docs/images/addAssignment.jpg
  docs/images/add_assignment_image.jpg
  docs/images/deleteAssignment.png
  docs/images/editStudent.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/resources/view/HelpWindow.css
Labels: type.Task, priority.High

#225 Duplicate names bug
  src/main/java/seedu/address/model/assignment/AssignmentName.java
  src/main/java/seedu/address/model/student/Name.java
  src/test/java/seedu/address/model/student/StudentTest.java
Labels: severity.Medium, alpha-bug

#226 UI update for assignment ID and student detail panel
  src/main/java/seedu/address/logic/commands/EditAssignmentCommand.java
  src/main/java/seedu/address/ui/StudentDetailsPanel.java
  src/main/resources/view/StudentDetailsPanel.fxml
Labels: type.Bug, priority.Medium, alpha-bug

#228 Update error message to use the ones in ParserUtil, and not just a generic Invalid Command Format error
  src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/GradeAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewStudentCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradeAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewStudentCommandParserTest.java
Labels: severity.Medium

#229 Improve error messages of indices and scores
  src/main/java/seedu/address/logic/parser/EditAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/test/java/seedu/address/logic/parser/EditAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradeAssignmentCommandParserTest.java
Labels: type.Bug, priority.High, alpha-bug

#231 Fix duplicate arguments and preamble argument
  src/main/java/seedu/address/logic/commands/EditAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/MarkAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/GradeAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkAssignmentCommandParser.java
Labels: priority.High, alpha-bug

#233 Update UG to include feature demo
  docs/UserGuide.md
  docs/images/editAssignment1.png
  docs/images/editAssignment2.png
  docs/images/gradeAssignment.png
Labels: type.Task, priority.Medium, alpha-bug

#241 Assignment is graded variable
  src/main/java/seedu/address/logic/commands/GradeAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAssignmentCommand.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/ui/StudentDetailsPanel.java
  src/test/java/seedu/address/model/assignment/AssignmentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedAssignmentTest.java
Labels: priority.High, severity.High, alpha-bug

#239 Fix bug in editAssignment and grade
  docs/UserGuide.md
Labels: type.Bug, alpha-bug

#237 Add Student Field Limits
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/Phone.java
  src/main/java/seedu/address/model/student/Remark.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, severity.High, alpha-bug

#244 Update dg biz use case
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/GradeAssignmentCommand.java
Labels: priority.High, severity.High, alpha-bug

#246 New image for UG fixing typo in editAssignment section
  docs/images/editAssignment1.png
Labels: type.Bug, alpha-bug

#247 Update UG to provide details of commands
  docs/UserGuide.md
  docs/images/addStudentExample.png
  docs/images/deleteStudentExample.png
Labels: severity.Low, alpha-bug

#248 Fix command box visibility
  docs/UserGuide.md
  docs/images/mark.png
  docs/images/remark.png
  docs/images/unmark.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/StudentDetailsPanel.fxml
  src/main/resources/view/StudentListCard.fxml
Labels: severity.High, alpha-bug

#232 Fix alpha bugs
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.High, alpha-bug

#236 Update UG with si/ prefix for Edit Student command and consistency
  docs/UserGuide.md
Labels: type.Task, priority.High

#253 Update UG and aligned feedback from invalid command
  docs/UserGuide.md
  docs/images/addAssignment.jpg
  docs/images/deleteAssignment.png
  docs/images/editStudent.png
  docs/images/gradeAssignment.png
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/EditAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/GradeAssignmentCommand.java
Labels: type.Task, priority.High

#255 Update user guide
  docs/UserGuide.md
Labels: priority.Medium

#259 Update DG and AD for Add Assignment
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/add-assignment/AddAssignmentActivityDiagram.puml
Labels: type.Task, priority.High

#260 Update images for editAssignment in UG
  docs/images/editAssignment1.png
  docs/images/editAssignment2.png
Labels: type.Task, type.Bug, alpha-bug

#327 Fix bugs emman
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug

#328 Update UG to fix bugs
  docs/UserGuide.md
Labels: type.Bug, severity.Medium

#329 Update DG to fix bugs
  docs/DeveloperGuide.md
Labels: type.Bug, severity.Medium

#330 Update DG
  docs/DeveloperGuide.md
Labels: type.Bug, severity.Medium

#331 Fix PE-D bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, priority.Medium

#332 Fix PE-D bugs in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, severity.Low

#333 Replace images
  docs/images/Ui.png
  docs/images/addStudentExample.png
  docs/images/deleteStudentExample.png
  docs/images/editAssignment1.png
  docs/images/editAssignment2.png
  docs/images/mark.png
  docs/images/remark.png
  docs/images/unmark.png
  src/main/resources/view/DarkTheme.css
Labels: type.Bug, severity.Low

#334 Update error messages
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ViewStudentCommandParser.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/test/java/seedu/address/logic/parser/ViewStudentCommandParserTest.java
Labels: type.Bug, severity.Medium

#335 Update isSameStudent method
  src/main/java/seedu/address/model/student/Student.java
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/java/seedu/address/model/student/StudentTest.java
Labels: type.Bug, severity.Medium

#337 Adjust for isSameStudent() change
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#339 Adjust for isSameStudent() change
  docs/UserGuide.md
Labels: type.Task, priority.High

#345 Add spacing
  docs/UserGuide.md
Labels: type.Task, severity.VeryLow
