Repository AY2425S1-CS2103-F11-1/tp, pull requests merged in 2024-10, with the labels that each got.

#38 Include use cases in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#39 Update Non-functional requirements and Glossary in DG
  docs/DeveloperGuide.md
Labels: type.Task

#45 Add assignment class
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/Name.java
Labels: priority.High

#49 Add assignment command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/AssignmentName.java
  src/main/java/seedu/address/model/assignment/UniqueAssignmentList.java
  src/main/java/seedu/address/model/assignment/exceptions/AssignmentNotFoundException.java
  src/main/java/seedu/address/model/assignment/exceptions/DuplicateAssignmentException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Task, priority.High, severity.High

#53 Edit product scope in DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#55 Update Storage to handle AssignmentList
  src/main/java/seedu/address/model/AddressBook.java
Labels: type.Task, priority.High

#60 Add assignment command
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Bug

#57 Add student field
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/exceptions/AssignmentAlreadyAssignedStudentException.java
  src/main/java/seedu/address/model/assignment/exceptions/AssignmentNotFoundException.java
  src/main/java/seedu/address/model/assignment/exceptions/DuplicateAssignmentException.java
Labels: priority.High

#58 Add details panel
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ViewStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewStudentCommandParser.java
  src/main/java/seedu/address/ui/BlankDetailsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/resources/view/BlankDetailsPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetailsPanel.fxml
Labels: type.Task

#64 Add new prefix for subject and grade and include this new prefix in AddCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Task

#65 Fix the bug of null StudentDetailsPanel in initialization
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudentDetailsPanel.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentDetailsPanel.fxml
Labels: type.Bug, severity.High

#68 Updates Assignment Command and Assignment class
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/UniqueAssignmentList.java
  src/main/java/seedu/address/model/assignment/exceptions/ScoreExceedsMaxScoreException.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/exceptions/AssignmentIndexOutOfRangeException.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentDetailsPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StudentDetailsPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: type.Task

#76 Update user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#86 Updates GradeAssignmentCommand to fix message
  build.gradle
  src/main/java/seedu/address/logic/commands/GradeAssignmentCommand.java
  src/main/java/seedu/address/model/assignment/Assignment.java
Labels: type.Bug, severity.VeryLow

#90 Add UI response to command
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/GradeAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/MarkAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAssignmentCommand.java
  src/main/resources/view/DarkTheme.css
Labels: priority.High

#92 GradeAssignmentCommand test
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/GradeAssignmentCommandTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalAssignments.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Task, priority.High

#87 Fix view student help
  src/main/java/seedu/address/logic/parser/ViewStudentCommandParser.java
Labels: type.Bug, severity.VeryLow

#97 Added mark assignment tests for equals and toString
  src/test/java/seedu/address/logic/commands/MarkAssignmentCommandTest.java
Labels: type.Task, priority.High

#98 Add unmark assignment tests for equals and toString
  src/test/java/seedu/address/logic/commands/UnmarkAssignmentCommandTest.java
Labels: type.Task, priority.High

#99 Create mark assignment parser tests
  src/main/java/seedu/address/logic/parser/MarkAssignmentCommandParser.java
  src/test/java/seedu/address/logic/parser/MarkAssignmentCommandParserTest.java
Labels: type.Task, priority.High

#100 Create unmark assignment parser tests
  src/test/java/seedu/address/logic/parser/UnmarkAssignmentCommandParserTest.java
Labels: type.Task, priority.High

#102 Create test cases for GradeAssignmentCommandParser
  src/main/java/seedu/address/logic/parser/GradeAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/GradeAssignmentCommandParserTest.java
Labels: type.Task, priority.High

#105 Fix view student help
  src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java
Labels: type.Bug, severity.VeryLow

#94 Add assignment test cases
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAssignmentCommandParserTest.java
Labels: priority.High

#103 Implement edit assignment functionality
  src/main/java/seedu/address/logic/commands/EditAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditAssignmentCommandParser.java
Labels: type.Task, priority.Medium

#109 Enable assertions in build.gradle
  build.gradle
Labels: type.Task

#107 Implement remark functionality
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentDetailsPanel.java
  src/main/resources/view/StudentDetailsPanel.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidStudentAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Task, priority.Medium

#118 Fix Constructor bug for Student class
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
Labels: type.Bug, priority.High

#122 Add test cases for remark implementation
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
Labels: type.Task, priority.High

#123 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/ViewStudentSequenceDiagram.puml
Labels: priority.High

#126 Update Developer Guide for remark
  docs/DeveloperGuide.md
  docs/diagrams/RemarkSequenceDiagram.puml
Labels: priority.Medium

#128 Fix UML diagrams
  docs/diagrams/RemarkSequenceDiagram.puml
  docs/diagrams/ViewStudentSequenceDiagram.puml
Labels: priority.Medium

#130 Fix minor bug in UML diagram
  docs/diagrams/RemarkSequenceDiagram.puml
  docs/diagrams/ViewStudentSequenceDiagram.puml
Labels: severity.High

#131 Add asserts
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/EditAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/GradeAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/MarkAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAssignmentCommand.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
Labels: type.Task

#134 Add template puml activity diagram for AddAssignment command
  docs/DeveloperGuide.md
  docs/diagrams/add-assignment/AddAssignmentActivityDiagram.puml
  docs/diagrams/add-assignment/AddAssignmentSequenceDiagram.puml
Labels: type.Task

#139 Correct pathing for uml diagrams
  docs/DeveloperGuide.md
Labels: type.Task

#137 Fix edit bug to retain assignment list and remark from the editted student
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/student/Student.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
Labels: type.Bug, priority.High

#143 Update the activity diagram for RemarkCommand
  docs/DeveloperGuide.md
  docs/diagrams/add-remark/RemarkCommandActivityDiagram.puml
Labels: type.Task, priority.Medium

#144 Fix the bug of missing endif
  docs/diagrams/add-remark/RemarkCommandActivityDiagram.puml
Labels: type.Bug, priority.Medium

#111 Fix bug when max scores were negative, and feedback given
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/GradeAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
Labels: type.Bug, severity.High

#146 Edit remark command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/student/Remark.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentDetailsPanel.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
Labels: type.Task, priority.High

#152 Add assignment name limit
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/assignment/AssignmentName.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentDetailsPanel.fxml
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: type.Task, priority.Medium

#158 Developer guide
  docs/DeveloperGuide.md
Labels: type.Task, severity.Medium

#149 Update AddAssignmentActivityDiagram
  docs/diagrams/add-assignment/AddAssignmentActivityDiagram.puml
Labels: type.Task, priority.High

#151 Remove reference from Assignment class to Student class
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/testutil/AssignmentBuilder.java
Labels: type.Task, priority.Medium

#185 Update user guide to add remark command
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#196 Update command descriptions
  src/main/java/seedu/address/logic/commands/MarkAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAssignmentCommand.java
Labels: severity.Low

#180 Update RemarkCommand Activity Diagram
  docs/diagrams/add-remark/RemarkCommandActivityDiagram.puml
Labels: type.Task, priority.High

#199 Remove unused Exceptions
  src/main/java/seedu/address/model/assignment/exceptions/AssignmentAlreadyAssignedStudentException.java
  src/main/java/seedu/address/model/assignment/exceptions/AssignmentNotFoundException.java
  src/main/java/seedu/address/model/assignment/exceptions/DuplicateAssignmentException.java
Labels: type.Task, priority.Low

#166 Enable text wrapping for long remarks
  src/main/resources/view/StudentDetailsPanel.fxml
Labels: type.Bug, severity.Medium
